name: Build and Deploy GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: Build
        run: python -m nitratine build
        env:
          YOUTUBE_DATA_API_KEY: ${{ secrets.YOUTUBE_DATA_API_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          cname: nitratine.net
          force_orphan: true # Only keep latest commit in gh-pages (to keep repo size down)

      - name: Get build stats
        run: |
          echo "Deployed master to prod" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          python -m nitratine stats >> $GITHUB_STEP_SUMMARY
        env:
          YOUTUBE_DATA_API_KEY: ${{ secrets.YOUTUBE_DATA_API_KEY }}
